# Generated by Django 4.0.4 on 2022-06-05 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('gabarit', models.CharField(max_length=20, verbose_name='Габариты')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=75, verbose_name='Адрес')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('tovarname', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('tovarid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tovar')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
